version: "1.0"
name: "fastify-4-migration-recipe"
description: "Complete migration recipe for upgrading to Fastify v4 - runs all individual codemods in sequence"

steps:
  - name: "Step 1: Transform fastify.register() calls to use await"
    action: "jssg"
    config:
      script: "../await-register-calls/scripts/codemod.ts"
      language: "typescript"
  
  - name: "Step 2: Add HEAD route exposure for GET routes"
    action: "jssg"
    config:
      script: "../expose-head-routes/scripts/codemod.ts"
      language: "typescript"
  
  - name: "Step 3: Remove deprecated app.use() calls"
    action: "jssg"
    config:
      script: "../remove-app-use/scripts/codemod.ts"
      language: "typescript"
  
  - name: "Step 4: Update reply.raw access patterns"
    action: "jssg"
    config:
      script: "../reply-raw-access/scripts/codemod.ts"
      language: "typescript"
  
  - name: "Step 5: Update URL parameter handling for optional parameters"
    action: "jssg"
    config:
      script: "../url-params-optional/scripts/codemod.ts"
      language: "typescript"
  
  - name: "Step 6: Suggest wrapping routes in plugins"
    action: "jssg"
    config:
      script: "../wrap-routes-plugin/scripts/codemod.ts"
      language: "typescript"
